#ifndef OVERLAP_H
#define OVERLAP_H

#define OPEN_PRAGMA {-#
#define CLOSE_PRAGMA #-}

#if __GLASGOW_HASKELL__ >= 710
# define __LANGUAGE_OVERLAPPING_INSTANCES__
# define __OVERLAPPABLE__ OPEN_PRAGMA OVERLAPPABLE CLOSE_PRAGMA
# define __OVERLAPPING__ OPEN_PRAGMA OVERLAPPING CLOSE_PRAGMA
# define __OVERLAPS__ OPEN_PRAGMA OVERLAPS CLOSE_PRAGMA
#else
# define __LANGUAGE_OVERLAPPING_INSTANCES__ OPEN_PRAGMA LANGUAGE OverlappingInstances CLOSE_PRAGMA
# define __OVERLAPPABLE__
# define __OVERLAPPING__
# define __OVERLAPS__
#endif

#endif
